Pr drone can support flight test patch
tridge/AM32 pull request #3
Opened 2024-09-19 07:38 UTC by Huibean

patch for first flight test
1.current value convert fix
2.add motor kv param

2024-09-19 08:39 UTC, tridge requested changes

2024-09-19 08:39 UTC, tridge commented on Src/DroneCAN/DroneCAN.c
> +                eepromBuffer[26] = (uint8_t)((*(uint16_t *)p->ptr - 20) / 40);
it would be good to have a comment explaining this :-)

2024-09-20 10:46 UTC, Huibean commented on Src/DroneCAN/DroneCAN.c
> +                eepromBuffer[26] = (uint8_t)((*(uint16_t *)p->ptr - 20) / 40);
change it to readable define EEPROM_MOTOR_KV_INDEX, btw, the code is tab and space mix a little bit mess to correct the format

2024-09-20 10:52 UTC, Huibean commented
3. add tune edit feature
work with dronecan gui tool in this PR https://github.com/dronecan/gui_tool/pull/62

2024-09-21 11:15 UTC, Huibean commented
4.add HSE support

2024-10-08 23:01 UTC, tridge commented
i've rebased this

2024-10-08 23:15 UTC, tridge approved these changes

2024-10-08 23:16 UTC, merged